### ISSUE TITLE
NodeComponent::getComponent returns incorrect type

### ISSUE THREAD

**Issue by Skurdt** [gingerBill/Dunjun#3]
```c++
template <class ComponentType>
NodeComponent& getComponent();
```
should be:
```c++
template <class ComponentType>
ComponentType& getComponent();
```

since you're using reinterpret_cast you most likely want to use the methods from the derived component after using getComponent.

**Comment by gingerBill** [comment]
Thank you for the issue. This will fixed in Day 070.
