### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by Sparkst3r** [gingerBill/Dunjun#9]
Hi Bill,
In your latest video (104) you briefly noted you didn't have a standard logging function. If you're interested, here's mine for my engine. It's open source so you are welcome to copy it.
I didn't fancy creating a pull request so I hope you don't mind me pasting a Dropbox link to it here.
https://dl.dropboxusercontent.com/u/45524288/Programming/LoggingManager.h
https://dl.dropboxusercontent.com/u/45524288/Programming/LoggingManager.cpp

Usage:
To use it you need an instance of the logger somewhere convenient.
e.g.
```cpp
LoggingManager log = LoggingManager();
```
It's also capable of outputting the log to file by specifying a filepath in the constructor.
```cpp
LoggingManager log = LoggingManager("path/to/file.txt");
```
To log some text you use the function like printf and you can specify where the log was sent from in owner:
```cpp
log(format, dataVarArgs);
log(logLevel, format, dataVarArgs);
log(owner, logLevel, format, dataVarArgs);
```

The main feature is colour coded text. UNIX support is unfinished but the windows log is just fine. All you need to do is append the UNIX color code. I don't have a linux or mac computer to test it though.

<img width="688" alt="img_45" src="https://cloud.githubusercontent.com/assets/3685781/9050051/3a4d0aac-3a41-11e5-818e-9a67a8bbabb8.png">

**Comment by gingerBill** [comment]
I will be very soon implementing a logging system. You kind of inferred what I was gonna do next!

It will work something like this:

```c++
Logger log = {};
log.file = stdout; // or iostream, I dunno yet
log.flags = LogFlag_Date | LogFlag_Time;
log.prefix = "Dunjun";
log.type = LogType::Log;
log.foreColor = LogColor::White;
log.backColor = LogColor::Black;
logPrintf(log, fmt, ...);
```
Example:
```c++
logPrint(warningLog, "%s is depreciated", "functionName()");
// [Prefix] 2015-08-04 23:59:59 functionName() is depreciated
```

It's a very simple implementation but it works. I've used something like this in numerous projects before.
